server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    #mybatis配置文件路径
  mapper-locations: classpath:mybatis/mapper/**/*.xml   #mapper映射文件
  type-aliases-package: com.shangguigu.entities

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource        #数据来源操作类型
    url: jdbc:mysql://132.232.59.22:3306/cloudDB03?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true      #数据库连接地址
    username: root
    password: 61154852a
    dbcp2:
      min-idle: 5                                       #数据库连接池的最小连接数
      initial-size: 5                                   #初始化连接数
      max-total: 5                                      #最大连接数
      max-wait-millis: 200                              #等待链接获取的最大超时时间
    driver-class-name: com.mysql.cj.jdbc.Driver         #mysql驱动包
  cloud:
    config:
      enabled: false
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8003 #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址
info:  #加入Eureka后显示的信息
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$